name: Sync to test2 repository

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Git
      run: |
        git config --global user.name 'GitHub Actions Sync'
        git config --global user.email 'noreply@github.com'
    
    - name: Clone target repository
      run: |
        git clone https://${{ secrets.SYNC_TOKEN }}@github.com/kyuri-code/test2.git target-repo
      env:
        SYNC_TOKEN: ${{ secrets.SYNC_TOKEN }}
    
    - name: Sync files to target repository
      run: |
        # Verify we're in the right place and remove existing files
        cd target-repo
        if [ ! -d ".git" ]; then
          echo "Error: Not in a git repository directory. Aborting."
          exit 1
        fi
        
        # Safely remove files, excluding .git
        find . -maxdepth 1 -type f -not -name '.gitignore' -delete 2>/dev/null || true
        find . -maxdepth 1 -type d -not -name '.git' -not -name '.' -not -name '..' -exec rm -rf {} + 2>/dev/null || true
        
        # Copy files using rsync for safety
        cd ..
        if command -v rsync >/dev/null 2>&1; then
          rsync -av --exclude='.git' --exclude='target-repo' --exclude='sync-to-test2.sh' . target-repo/
        else
          # Fallback to explicit copying
          find . -maxdepth 1 -type f -not -name 'sync-to-test2.sh' -exec cp {} target-repo/ \;
          find . -maxdepth 1 -type d -not -name '.git' -not -name 'target-repo' -not -name '.' -not -name '..' -exec cp -r {} target-repo/ \;
        fi
        
        # Stage changes
        cd target-repo
        git add .
        echo "Files staged for commit:"
        git status --porcelain
    
    - name: Commit and push changes
      run: |
        cd target-repo
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Sync from kyuri-code/test - $(date)"
          git push origin main
        fi
      env:
        SYNC_TOKEN: ${{ secrets.SYNC_TOKEN }}