name: Sync to test2 repository

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
    
    - name: Clone target repository
      run: |
        git clone https://${{ secrets.SYNC_TOKEN }}@github.com/kyuri-code/test2.git target-repo
      env:
        SYNC_TOKEN: ${{ secrets.SYNC_TOKEN }}
    
    - name: Sync files to target repository
      run: |
        # Remove existing files in target repo (except .git)
        cd target-repo
        find . -maxdepth 1 -not -name '.git' -not -name '.' -not -name '..' -exec rm -rf {} + 2>/dev/null || true
        
        # Copy all files from source to target (except .git and sync script)
        cd ..
        find . -maxdepth 1 -not -name '.git' -not -name 'target-repo' -not -name 'sync-to-test2.sh' -not -name '.' -not -name '..' -exec cp -r {} target-repo/ \;
        
        # Stage changes
        cd target-repo
        git add .
        echo "Files staged for commit:"
        git status --porcelain
    
    - name: Commit and push changes
      run: |
        cd target-repo
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Sync from kyuri-code/test - $(date)"
          git push origin main
        fi
      env:
        SYNC_TOKEN: ${{ secrets.SYNC_TOKEN }}